exclude:
- /.eslintrc.js
- /build/.*
- /config/.*
- .*/TestDetailQuestions.vue
- .*/AddLanguage.vue
- .*/UsersList.vue
- .*/WorkPositions.vue
- .*/CreatedTestsList.vue
component_depth: 1
languages:
- name: javascript
  production:
    include:
      - .*\.vue
      - .*\.js
